version: '3'
services:
  jupyterlab:
    build: .
    runtime: nvidia
    ports:
      - '8888:8888'
    command:
      jupyter lab
          --ip=0.0.0.0
          --allow-root
          --NotebookApp.token=''
    volumes:
      - ./work:/home/tux
    env_file:
      - .id.env
